"""
=============================================================================
AETHELNET NEUROSYMBOLIC DSL & DETERMINISTIC SOLVER FOR ARC-AGI-3
=============================================================================
Provides clean, mathematically sound primitives for both:
1. Direct autonomous execution by the Active Inference Engine.
2. High-level macro execution from Python code generated by the LLM (vLLM / Qwen).

Zero hardcoded game IDs.
Zero hardcoded coordinates or move recordings.
100% Domain-Agnostic.
=============================================================================
"""

import sys
import math
import json
import heapq
import itertools
import collections
from pathlib import Path
from dataclasses import dataclass, asdict, field
from typing import Dict, List, Tuple, Set, Optional, Any, Union
import numpy as np

# Action names standard
ACTION_UP = 'ACTION1'
ACTION_DOWN = 'ACTION2'
ACTION_LEFT = 'ACTION3'
ACTION_RIGHT = 'ACTION4'
ACTION_RESET = 'RESET'
ACTION_CLICK = 'ACTION6'

ACTION_TO_DIR = {
    1: (-1, 0), 2: (1, 0), 3: (0, -1), 4: (0, 1),
    'ACTION1': (-1, 0), 'ACTION2': (1, 0), 'ACTION3': (0, -1), 'ACTION4': (0, 1),
    'UP': (-1, 0), 'DOWN': (1, 0), 'LEFT': (0, -1), 'RIGHT': (0, 1),
}

DIR_TO_ACTION_NAME = {
    (-1, 0): 'ACTION1',
    (1, 0): 'ACTION2',
    (0, -1): 'ACTION3',
    (0, 1): 'ACTION4',
}

DIR_TO_ACTION_INT = {
    (-1, 0): 1,
    (1, 0): 2,
    (0, -1): 3,
    (0, 1): 4,
}

ACTION_TO_NAME = {
    1: 'UP',
    2: 'DOWN',
    3: 'LEFT',
    4: 'RIGHT',
    'ACTION1': 'UP',
    'ACTION2': 'DOWN',
    'ACTION3': 'LEFT',
    'ACTION4': 'RIGHT',
}


# =============================================================================
# 1. Perception & Structural Analysis
# =============================================================================

def get_background_color(grid: np.ndarray) -> int:
    """Finds dominant background color of the grid."""
    grid = np.asarray(grid)
    vals, counts = np.unique(grid, return_counts=True)
    return int(vals[np.argmax(counts)])


def detect_hud_bars(g0: np.ndarray, g1: np.ndarray, border_band: int = 2) -> Tuple[Set[int], Set[int]]:
    """Identifies border rows and columns that only act as counters/HUD ticks."""
    H, W = g0.shape
    diff = (g0 != g1)
    hud_rows, hud_cols = set(), set()
    if not np.any(diff):
        return hud_rows, hud_cols

    diff_pts = np.argwhere(diff)
    for r, c in diff_pts:
        if r < border_band or r >= H - border_band:
            if 1 <= diff[r, :].sum() <= 4:
                hud_rows.add(r)
        if c < border_band or c >= W - border_band:
            if 1 <= diff[:, c].sum() <= 4:
                hud_cols.add(c)
    return hud_rows, hud_cols


def extract_clickable_targets(
    grid: np.ndarray,
    hud_rows: Optional[Set[int]] = None,
    hud_cols: Optional[Set[int]] = None,
    min_area: int = 4,
    max_area: Optional[int] = None
) -> List[Tuple[int, int]]:
    """
    Identifies centroid (x, y) coordinates of distinct clickable interactive buttons/sprites.
    Returns sorted by rarity (smallest/rarest components first).
    """
    grid = np.asarray(grid)
    H, W = grid.shape
    bg = get_background_color(grid)
    hud_r = hud_rows or set()
    hud_c = hud_cols or set()
    if max_area is None:
        max_area = (H * W) // 4

    visited = np.zeros((H, W), dtype=bool)
    components = []

    for r in range(H):
        for c in range(W):
            if visited[r, c] or grid[r, c] == bg or r in hud_r or c in hud_c:
                continue
            color = grid[r, c]
            q = [(r, c)]
            visited[r, c] = True
            comp_pts = []
            min_r, max_r, min_c, max_c = r, r, c, c

            while q:
                cr, cc = q.pop(0)
                comp_pts.append((cr, cc))
                min_r = min(min_r, cr)
                max_r = max(max_r, cr)
                min_c = min(min_c, cc)
                max_c = max(max_c, cc)

                for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                    nr, nc = cr + dr, cc + dc
                    if 0 <= nr < H and 0 <= nc < W:
                        if not visited[nr, nc] and grid[nr, nc] == color and nr not in hud_r and nc not in hud_c:
                            visited[nr, nc] = True
                            q.append((nr, nc))

            if min_area <= len(comp_pts) <= max_area:
                center_r = (min_r + max_r) // 2
                center_c = (min_c + max_c) // 2
                components.append((center_c, center_r, len(comp_pts), color))

    components.sort(key=lambda x: (x[2], x[0], x[1]))
    return [(c, r) for c, r, _, _ in components]


# =============================================================================
# 2. Kinematics Induction (Stride, Avatar, Background)
# =============================================================================

class KinematicsProfile:
    def __init__(
        self,
        stride: int = 1,
        avatar_shape: Tuple[int, int] = (1, 1),
        avatar_colors: Optional[Set[int]] = None,
        bg_color: int = 0
    ):
        self.stride = stride
        self.avatar_shape = avatar_shape
        self.avatar_colors = avatar_colors or set()
        self.bg_color = bg_color


def calibrate_kinematics_probe(
    g0: np.ndarray,
    g1: np.ndarray,
    action: Union[int, str]
) -> Optional[KinematicsProfile]:
    """
    Given two consecutive grids (before & after move) and the action executed,
    uses connected component analysis to ground physical stride, avatar bounding box,
    avatar pixel colors, and background color.
    """
    from scipy.ndimage import label
    g0 = np.asarray(g0)
    g1 = np.asarray(g1)
    H, W = g0.shape
    diff = (g0 != g1)
    if not np.any(diff):
        return None

    lbl, n = label(diff)
    best_comp = None
    best_area = -1

    for i in range(1, n + 1):
        comp = np.argwhere(lbl == i)
        area = len(comp)
        if area <= 4:
            continue
        if area > best_area:
            best_area = area
            r0, c0 = comp.min(axis=0)
            r1, c1 = comp.max(axis=0)
            best_comp = (comp, r0, c0, r1, c1, r1 - r0 + 1, c1 - c0 + 1)

    if best_comp is None:
        return None

    comp, r0, c0, r1, c1, h_diff, w_diff = best_comp
    dr, dc = ACTION_TO_DIR.get(action, (0, 0))

    if dr > 0:  # DOWN
        stride = max(1, h_diff // 2)
        old_patch = g1[r0:r0 + stride, c0:c1 + 1]
        new_patch = g1[r0 + stride:r1 + 1, c0:c1 + 1]
        shape = (stride, w_diff)
    elif dr < 0:  # UP
        stride = max(1, h_diff // 2)
        old_patch = g1[r1 - stride + 1:r1 + 1, c0:c1 + 1]
        new_patch = g1[r0:r1 - stride + 1, c0:c1 + 1]
        shape = (stride, w_diff)
    elif dc > 0:  # RIGHT
        stride = max(1, w_diff // 2)
        old_patch = g1[r0:r1 + 1, c0:c0 + stride]
        new_patch = g1[r0:r1 + 1, c0 + stride:c1 + 1]
        shape = (h_diff, stride)
    else:  # LEFT
        stride = max(1, w_diff // 2)
        old_patch = g1[r0:r1 + 1, c1 - stride + 1:c1 + 1]
        new_patch = g1[r0:r1 + 1, c0:c1 - stride + 1]
        shape = (h_diff, stride)

    bg_color = int(np.bincount(old_patch.flatten()).argmax())
    av_colors = set(int(c) for c in np.unique(new_patch)) - {bg_color}
    return KinematicsProfile(stride=stride, avatar_shape=shape, avatar_colors=av_colors, bg_color=bg_color)


def locate_avatar_on_grid(
    grid: np.ndarray,
    profile: KinematicsProfile,
    hud_rows: Optional[Set[int]] = None,
    hud_cols: Optional[Set[int]] = None
) -> Optional[Tuple[int, int]]:
    """Locates top-left (r, c) of the player avatar using induced kinematics."""
    if not profile.avatar_colors:
        return None
    H, W = grid.shape
    ah, aw = profile.avatar_shape
    s = profile.stride
    hud_r = hud_rows or set()
    hud_c = hud_cols or set()

    best_pos = None
    best_score = -1

    for r in range(0, H - ah + 1, s):
        if r in hud_r:
            continue
        for c in range(0, W - aw + 1, s):
            if c in hud_c:
                continue
            patch = grid[r:r + ah, c:c + aw]
            matches = sum(1 for v in patch.flat if v in profile.avatar_colors)
            if matches > best_score and matches >= max(1, (ah * aw) // 3):
                best_score = matches
                best_pos = (r, c)

    return best_pos


# =============================================================================
# 3. Pathfinding (BFS / A*)
# =============================================================================

def plan_bfs_path(
    start_pos: Tuple[int, int],
    target_pos: Tuple[int, int],
    solid_mask: np.ndarray,
    stride: int = 1,
    deadly_coords: Optional[Set[Tuple[int, int]]] = None,
    legal_actions: Optional[List[Any]] = None,
    as_strings: bool = True
) -> List[Any]:
    """
    Sub-millisecond BFS grid pathfinding over arbitrary solid obstacles & fatal tiles.
    """
    sr, sc = start_pos
    tr, tc = target_pos
    s = stride
    if solid_mask is None or not hasattr(solid_mask, "shape") or len(solid_mask.shape) != 2:
        return []
    H, W = solid_mask.shape
    hazards = deadly_coords or set()

    q = [(sr, sc, [])]
    visited = {(sr, sc)}

    allowed_moves = [1, 2, 3, 4]
    if legal_actions:
        allowed_moves = [
            DIR_TO_ACTION_INT[ACTION_TO_DIR[a]]
            for a in legal_actions
            if a in ACTION_TO_DIR
        ]

    while q:
        cr, cc, path = q.pop(0)
        if abs(cr - tr) < s and abs(cc - tc) < s:
            if as_strings:
                return [DIR_TO_ACTION_NAME[ACTION_TO_DIR[act]] for act in path]
            return path

        if len(path) > 120:
            continue

        for act in allowed_moves:
            dr, dc = ACTION_TO_DIR[act]
            nr, nc = cr + dr * s, cc + dc * s

            if 0 <= nr <= H - s and 0 <= nc <= W - s:
                if np.any(solid_mask[nr:nr + s, nc:nc + s]):
                    continue
                if (nr, nc) in hazards:
                    continue
                if (nr, nc) not in visited:
                    visited.add((nr, nc))
                    q.append((nr, nc, path + [act]))

    return []


# =============================================================================
# 4. Sokoban / Push-A* Routing
# =============================================================================

def plan_push_box(
    avatar_pos: Tuple[int, int],
    box_pos: Tuple[int, int],
    target_slot: Tuple[int, int],
    solid_mask: np.ndarray,
    stride: int = 1,
    as_strings: bool = True
) -> List[Any]:
    """
    Push-A* Sokoban planner:
    Calculates push trajectory to move box into target_slot,
    generating avatar navigation moves to the push pose behind the box for each push.
    """
    s = stride
    if solid_mask is None or not hasattr(solid_mask, "shape") or len(solid_mask.shape) != 2:
        return []
    H, W = solid_mask.shape

    # State: (box_r, box_c, avatar_r, avatar_c)
    # A* search over box positions
    open_heap = []
    # (f_cost, g_cost, (box_r, box_c), (av_r, av_c), moves_list)
    h0 = (abs(box_pos[0] - target_slot[0]) + abs(box_pos[1] - target_slot[1])) // s
    heapq.heappush(open_heap, (h0, 0, box_pos, avatar_pos, []))
    visited_states = set()

    while open_heap:
        f, g, b_curr, a_curr, moves = heapq.heappop(open_heap)
        if abs(b_curr[0] - target_slot[0]) < s and abs(b_curr[1] - target_slot[1]) < s:
            if as_strings:
                return [DIR_TO_ACTION_NAME[ACTION_TO_DIR[m]] if isinstance(m, int) else m for m in moves]
            return moves

        state_key = (b_curr, a_curr)
        if state_key in visited_states or len(moves) > 150:
            continue
        visited_states.add(state_key)

        # Try pushing box in 4 directions
        for d_act in [1, 2, 3, 4]:
            dr, dc = ACTION_TO_DIR[d_act]
            next_b = (b_curr[0] + dr * s, b_curr[1] + dc * s)
            push_pose = (b_curr[0] - dr * s, b_curr[1] - dc * s)

            # Check next box validity
            if not (0 <= next_b[0] <= H - s and 0 <= next_b[1] <= W - s):
                continue
            if np.any(solid_mask[next_b[0]:next_b[0] + s, next_b[1]:next_b[1] + s]):
                continue

            # Check push pose validity
            if not (0 <= push_pose[0] <= H - s and 0 <= push_pose[1] <= W - s):
                continue
            if np.any(solid_mask[push_pose[0]:push_pose[0] + s, push_pose[1]:push_pose[1] + s]):
                continue

            # Route avatar to push pose treating box as obstacle
            box_barrier = solid_mask.copy()
            box_barrier[b_curr[0]:b_curr[0] + s, b_curr[1]:b_curr[1] + s] = True

            nav_moves = plan_bfs_path(a_curr, push_pose, box_barrier, stride=s, as_strings=False)
            if a_curr == push_pose or nav_moves or (abs(a_curr[0] - push_pose[0]) < s and abs(a_curr[1] - push_pose[1]) < s):
                total_step_moves = moves + nav_moves + [d_act]
                new_av = b_curr  # Avatar moves into old box position
                new_g = g + len(nav_moves) + 1
                new_h = (abs(next_b[0] - target_slot[0]) + abs(next_b[1] - target_slot[1])) // s
                heapq.heappush(open_heap, (new_g + new_h, new_g, next_b, new_av, total_step_moves))

    return []


# =============================================================================
# 5. Galois Field GF(k) Modular Linear Solver
# =============================================================================

def solve_modular_linear_system(
    A: np.ndarray,
    b: np.ndarray,
    k: int = 2
) -> Optional[np.ndarray]:
    """
    Exact Gaussian elimination solving A x ≡ b (mod k).
    Used for toggle switches, light bulbs, parity constraints, and GF(2) circuits.
    Minimizes total switch clicks sum(x).
    """
    A = np.asarray(A, dtype=int) % k
    b = np.asarray(b, dtype=int).flatten() % k
    n_rows, n_cols = A.shape
    M = np.hstack([A, b.reshape(-1, 1)]) % k

    row = 0
    pivots = []
    pivot_cols = set()

    for col in range(n_cols):
        p = None
        for r in range(row, n_rows):
            val = int(M[r, col] % k)
            if val != 0:
                if math.gcd(val, k) == 1:
                    p = r
                    break
                elif p is None:
                    p = r
        if p is None:
            continue

        M[[row, p]] = M[[p, row]]
        pivot_val = int(M[row, col])
        try:
            inv = pow(pivot_val, -1, k)
        except ValueError:
            continue

        M[row] = (M[row] * inv) % k
        for r in range(n_rows):
            if r != row and M[r, col] % k != 0:
                factor = M[r, col]
                M[r] = (M[r] - factor * M[row]) % k
        pivots.append((row, col))
        pivot_cols.add(col)
        row += 1

    # Consistency check
    for r in range(row, n_rows):
        if M[r, -1] % k != 0:
            return None

    free_cols = [c for c in range(n_cols) if c not in pivot_cols]

    if not free_cols:
        x_sol = np.zeros(n_cols, dtype=int)
        for r, col in reversed(pivots):
            x_sol[col] = (M[r, -1] - np.dot(M[r, :n_cols], x_sol)) % k
        return x_sol

    # Multiple solutions exist: search nullspace minimizing sum(x)
    best_x = None
    min_clicks = float('inf')
    max_search = min(len(free_cols), 6)

    for free_vals in itertools.product(range(k), repeat=max_search):
        x_cand = np.zeros(n_cols, dtype=int)
        for i, val in enumerate(free_vals):
            x_cand[free_cols[i]] = val
        for r, col in reversed(pivots):
            x_cand[col] = (M[r, -1] - np.dot(M[r, :n_cols], x_cand)) % k

        clicks = int(np.sum(x_cand))
        if clicks < min_clicks:
            min_clicks = clicks
            best_x = x_cand

    return best_x


# =============================================================================
# 6. Autonomous Active Inference Solver (Engine Fallback)
# =============================================================================

class RealActiveInferenceSolver:
    """
    Full autonomous active inference player for any ARC-AGI-3 environment.
    Runs whenever the LLM is dormant, stalled, or when low-level execution is needed.
    """
    def __init__(self, game_id: str = "default"):
        self.game_id = game_id
        self.level_resets = collections.defaultdict(int)
        self.reset_all()

    def reset_all(self):
        self.current_level = 0
        self.step_count = 0
        self.prev_grid = None
        self.last_action = None
        self.last_action_data = None
        self.calibrated = False
        self.probe_step = 0
        self.profile = KinematicsProfile()
        self.avatar_pos = None
        self.hud_rows = set()
        self.hud_cols = set()
        self.deadly_coords = set()
        self.visited_tiles = set()
        self.visit_counts = collections.defaultdict(int)
        self.plan_queue = []
        self.click_queue = []
        self.click_tested = set()
        self.level_resets.clear()

    def reset_level(self, level: int):
        self.current_level = level
        self.prev_grid = None
        self.last_action = None
        self.last_action_data = None
        self.plan_queue.clear()
        self.click_queue.clear()
        self.visited_tiles.clear()
        self.visit_counts.clear()
        self.avatar_pos = None

    def choose_action(
        self,
        grid: np.ndarray,
        available_actions: List[int],
        levels_completed: int,
        state_name: str
    ) -> Tuple[int, Optional[Dict[str, Any]], str]:
        self.step_count += 1
        grid = np.asarray(grid)

        # 1. Level Transition Handler
        if levels_completed > self.current_level:
            self.reset_level(levels_completed)

        # 2. Episodic Death Memory & Reset Handler
        if state_name in ('GAME_OVER', 'NOT_PLAYED'):
            if state_name == 'GAME_OVER' and self.avatar_pos is not None and self.last_action in ACTION_TO_DIR:
                dr, dc = ACTION_TO_DIR[self.last_action]
                s = self.profile.stride
                fatal_r = self.avatar_pos[0] + dr * s
                fatal_c = self.avatar_pos[1] + dc * s
                self.deadly_coords.add((fatal_r, fatal_c))
            self.reset_level(levels_completed)
            return (0, None, "GameReset")

        # 2b. Controlled Reset on Irreversible Cargo Deadlock
        _, entities = AethelnetGameOntology.extract_entities(grid)
        goals = set()
        for e in entities:
            if e.archetype == "GOAL" and e.archetype not in ("HUD", "OBSTACLE"):
                min_r, min_c, max_r, max_c = e.bbox
                for r in range(min_r, max_r + 1):
                    for c in range(min_c, max_c + 1):
                        goals.add((r, c))
                goals.add(e.center)
        cargos = [e for e in entities if e.archetype in ("PUSHABLE", "ACTUATOR") and not e.is_hollow and e.area >= 2]

        vault = AethelnetVault.get_instance(self.game_id)
        if cargos and (0 in available_actions or 'RESET' in available_actions):
            for cargo in cargos:
                if is_corner_deadlock(grid, cargo.bbox, goals) or is_corner_deadlock(grid, cargo.center, goals):
                    if self.level_resets[levels_completed] < 2:
                        self.level_resets[levels_completed] += 1
                        sig = f"lvl{levels_completed}_box{cargo.center}"
                        vault.remember_nogood(
                            level=levels_completed,
                            state_signature=sig,
                            forbidden_action=self.last_action if self.last_action is not None else 0,
                            reason=f"Cargo at {cargo.center} permanently trapped in non-goal corner",
                            turn=self.step_count
                        )
                        self.reset_level(levels_completed)
                        return (0, None, f"ControlledReset_DeadlockCargo_{cargo.center}")

        # 3. Pure Click Mode Handler (Action 6 only)
        is_pure_click = (available_actions == [6]) or (6 in available_actions and not any(a in [1, 2, 3, 4] for a in available_actions))
        if is_pure_click:
            if not self.click_queue:
                centroids = extract_clickable_targets(grid, self.hud_rows, self.hud_cols)
                self.click_queue = [pt for pt in centroids if pt not in self.click_tested]
                if not self.click_queue:
                    self.click_queue = centroids

            if self.click_queue:
                cx, cy = self.click_queue.pop(0)
                self.click_tested.add((cx, cy))
                self.last_action = 6
                self.last_action_data = {'x': int(cx), 'y': int(cy)}
                self.prev_grid = grid.copy()
                return (6, {'x': int(cx), 'y': int(cy)}, f"ClickTarget_{cx}_{cy}")

        # 4. Plan Queue Execution
        if self.plan_queue:
            act, data = self.plan_queue.pop(0)
            if act in available_actions:
                vetoed = False
                if act in ACTION_TO_DIR and self.avatar_pos is not None:
                    ar, ac = self.avatar_pos
                    dr, dc = ACTION_TO_DIR[act]
                    s = self.profile.stride
                    nr, nc = ar + dr * s, ac + dc * s
                    for cargo in cargos:
                        min_r, min_c, max_r, max_c = cargo.bbox
                        if min_r <= nr <= max_r and min_c <= nc <= max_c:
                            deadlock, _ = evaluate_push_deadlock(grid, cargo.center, act, goals)
                            if deadlock:
                                vetoed = True
                                break
                if vetoed:
                    self.plan_queue.clear()
                else:
                    self.last_action = act
                    self.last_action_data = data
                    self.prev_grid = grid.copy()
                    return (act, data, "ExecutingPlan")
            else:
                self.plan_queue.clear()

        # 5. Calibration Probe
        if not self.calibrated:
            if self.prev_grid is not None and self.last_action is not None:
                hr, hc = detect_hud_bars(self.prev_grid, grid)
                self.hud_rows.update(hr)
                self.hud_cols.update(hc)
                prof = calibrate_kinematics_probe(self.prev_grid, grid, self.last_action)
                if prof is not None:
                    self.profile = prof
                    self.calibrated = True
                    self.avatar_pos = locate_avatar_on_grid(grid, self.profile, self.hud_rows, self.hud_cols)

            if not self.calibrated:
                probe_cands = [a for a in [4, 2, 3, 1] if a in available_actions]
                act = probe_cands[self.probe_step % len(probe_cands)] if probe_cands else available_actions[0]
                self.probe_step += 1
                self.last_action = act
                self.last_action_data = None
                self.prev_grid = grid.copy()
                return (act, None, f"CalibrationProbe_{act}")

        # 6. Locate Avatar
        self.avatar_pos = locate_avatar_on_grid(grid, self.profile, self.hud_rows, self.hud_cols)

        # 7. Navigation & Goal Seeking
        if self.avatar_pos is not None:
            H, W = grid.shape
            bg = get_background_color(grid)
            counts = collections.Counter(grid.flatten())
            non_bg = [c for c, _ in counts.most_common() if c != bg]
            wall_color = non_bg[0] if non_bg else bg
            solid_mask = (grid == wall_color)

            for hr in self.hud_rows:
                solid_mask[hr, :] = True
            for hc in self.hud_cols:
                solid_mask[:, hc] = True

            centroids = extract_clickable_targets(grid, self.hud_rows, self.hud_cols)
            ar, ac = self.avatar_pos

            for target_c, target_r in centroids:
                if (target_r, target_c) == (ar, ac):
                    continue
                path = plan_bfs_path((ar, ac), (target_r, target_c), solid_mask, stride=self.profile.stride,
                                     deadly_coords=self.deadly_coords, legal_actions=available_actions, as_strings=False)
                if path:
                    first_act = path[0]
                    self.plan_queue = [(a, None) for a in path[1:]]
                    self.last_action = first_act
                    self.last_action_data = None
                    self.prev_grid = grid.copy()
                    return (first_act, None, f"NavigatingTo_{target_r}_{target_c}")

            # Fallback: exploratory move minimizing visit counts & vetoing deadlocks
            self.visit_counts[self.avatar_pos] += 1
            legal_moves = [a for a in [1, 2, 3, 4] if a in available_actions]
            s = self.profile.stride
            best_act = None
            min_visits = 999999

            for act in legal_moves:
                dr, dc = ACTION_TO_DIR[act]
                nr, nc = ar + dr * s, ac + dc * s
                if 0 <= nr <= H - s and 0 <= nc <= W - s:
                    if not np.any(solid_mask[nr:nr + s, nc:nc + s]) and (nr, nc) not in self.deadly_coords:
                        # Deadlock veto for pushable entities
                        is_deadlock = False
                        for cargo in cargos:
                            min_r, min_c, max_r, max_c = cargo.bbox
                            if min_r <= nr <= max_r and min_c <= nc <= max_c:
                                deadlock, reason = evaluate_push_deadlock(grid, cargo.center, act, goals)
                                if deadlock:
                                    is_deadlock = True
                                    sig = f"lvl{levels_completed}_box{cargo.center}_av({ar},{ac})"
                                    vault.remember_nogood(levels_completed, sig, act, reason or "Corner deadlock", turn=self.step_count)
                                    break
                        if is_deadlock:
                            continue

                        # Conflict-driven nogood clause check
                        sig1 = f"lvl{levels_completed}_av({ar},{ac})"
                        is_ng, _ = vault.is_action_nogood(levels_completed, sig1, act)
                        if not is_ng:
                            for cargo in cargos:
                                sig2 = f"lvl{levels_completed}_box{cargo.center}_av({ar},{ac})"
                                is_ng2, _ = vault.is_action_nogood(levels_completed, sig2, act)
                                if is_ng2:
                                    is_ng = True
                                    break
                        if is_ng:
                            continue

                        vc = self.visit_counts[(nr, nc)]
                        if vc < min_visits:
                            min_visits = vc
                            best_act = act

            if best_act is not None:
                self.last_action = best_act
                self.last_action_data = None
                self.prev_grid = grid.copy()
                return (best_act, None, f"ExploratoryMove_{best_act}")

        # 8. Dynamic Legal Fallback
        cands = [a for a in available_actions if a != 0]
        act = cands[0] if cands else 1
        data = None
        if act == 6:
            centroids = extract_clickable_targets(grid, self.hud_rows, self.hud_cols)
            cx, cy = centroids[0] if centroids else (32, 32)
            data = {'x': int(cx), 'y': int(cy)}

        self.last_action = act
        self.last_action_data = data
        self.prev_grid = grid.copy()
        return (int(act), data, "DynamicFallback")


# =============================================================================
# 6. Aethelnet Causal Vault & Episodic Memory Scratchpad (Phase 345 / v37)
# =============================================================================

@dataclass
class CausalFact:
    subject: str
    relation: str
    target: str
    confidence: float = 1.0
    turn: int = 0
    tag: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "subject": self.subject,
            "relation": self.relation,
            "target": self.target,
            "confidence": self.confidence,
            "turn": self.turn,
            "tag": self.tag,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> 'CausalFact':
        return cls(
            subject=str(d.get("subject", "")),
            relation=str(d.get("relation", "")),
            target=str(d.get("target", "")),
            confidence=float(d.get("confidence", 1.0)),
            turn=int(d.get("turn", 0)),
            tag=str(d.get("tag", "")),
        )


@dataclass
class NogoodClause:
    level: int
    state_signature: str
    forbidden_action: Any
    reason: str
    turn: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "level": self.level,
            "state_signature": self.state_signature,
            "forbidden_action": self.forbidden_action,
            "reason": self.reason,
            "turn": self.turn,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> 'NogoodClause':
        return cls(
            level=int(d.get("level", 0)),
            state_signature=str(d.get("state_signature", "")),
            forbidden_action=d.get("forbidden_action"),
            reason=str(d.get("reason", "")),
            turn=int(d.get("turn", 0)),
        )


class AethelnetVault:
    _instances: Dict[str, 'AethelnetVault'] = {}

    def __init__(self, game_id: str, storage_dir: str = "/kaggle/working"):
        self.game_id = game_id
        self.storage_dir = Path(storage_dir)
        self.storage_path = self.storage_dir / f"aethelnet_vault_{game_id}.json"
        self.facts: List[CausalFact] = []
        self.nogoods: List[NogoodClause] = []
        self.scratchpad: Dict[str, Any] = {}
        self.load()

    @classmethod
    def get_instance(cls, game_id: str = "default", storage_dir: str = "/kaggle/working") -> 'AethelnetVault':
        if game_id not in cls._instances:
            cls._instances[game_id] = cls(game_id, storage_dir=storage_dir)
        return cls._instances[game_id]

    def remember(
        self,
        subject: str,
        relation: str,
        target: str,
        confidence: float = 1.0,
        turn: int = 0,
        tag: str = ""
    ) -> CausalFact:
        for f in self.facts:
            if f.subject == subject and f.relation == relation and f.target == target:
                f.confidence = max(f.confidence, float(confidence))
                f.turn = turn
                if tag:
                    f.tag = tag
                self.save()
                return f
        new_fact = CausalFact(subject, relation, target, float(confidence), turn, tag)
        self.facts.append(new_fact)
        self.save()
        return new_fact

    def recall(
        self,
        subject: Optional[str] = None,
        relation: Optional[str] = None,
        min_confidence: float = 0.5
    ) -> List[CausalFact]:
        results = []
        for f in self.facts:
            if f.confidence < min_confidence:
                continue
            if subject is not None and f.subject != subject:
                continue
            if relation is not None and f.relation != relation:
                continue
            results.append(f)
        return sorted(results, key=lambda x: (x.confidence, x.turn), reverse=True)

    def remember_nogood(
        self,
        level: int,
        state_signature: str,
        forbidden_action: Any,
        reason: str,
        turn: int = 0
    ) -> NogoodClause:
        for ng in self.nogoods:
            if ng.level == level and ng.state_signature == state_signature and ng.forbidden_action == forbidden_action:
                ng.turn = turn
                ng.reason = reason
                self.save()
                return ng
        new_ng = NogoodClause(level, state_signature, forbidden_action, reason, turn)
        self.nogoods.append(new_ng)
        self.save()
        return new_ng

    def is_action_nogood(self, level: int, state_signature: str, action: Any) -> Tuple[bool, Optional[str]]:
        for ng in self.nogoods:
            if ng.level == level and ng.state_signature == state_signature and ng.forbidden_action == action:
                return True, ng.reason
        return False, None

    def get_nogoods_for_level(self, level: int) -> List[NogoodClause]:
        return [ng for ng in self.nogoods if ng.level == level]

    def set_scratchpad(self, key: str, value: Any):
        self.scratchpad[key] = value

    def get_scratchpad(self, key: str, default: Any = None) -> Any:
        return self.scratchpad.get(key, default)

    def observe_grid_delta(self, prev_grid: np.ndarray, curr_grid: np.ndarray, action: Any, turn: int = 0):
        """Automatically evaluates state transition and extracts causal rules."""
        if prev_grid is None or curr_grid is None:
            return
        if getattr(prev_grid, "shape", None) != getattr(curr_grid, "shape", None):
            return
        diff = (prev_grid != curr_grid)
        num_changed = int(np.sum(diff))
        if num_changed == 0:
            return

        # Check if specific colors disappeared or changed
        prev_colors, prev_counts = np.unique(prev_grid, return_counts=True)
        curr_colors, curr_counts = np.unique(curr_grid, return_counts=True)
        prev_dict = dict(zip(prev_colors, prev_counts))
        curr_dict = dict(zip(curr_colors, curr_counts))

        for c, count in prev_dict.items():
            lost = count - curr_dict.get(c, 0)
            if lost >= 3:
                self.remember(
                    subject=f"action_{action}",
                    relation="removed_or_unlocked",
                    target=f"color_{c}_pixels({lost})",
                    confidence=0.95,
                    turn=turn,
                    tag="auto_delta"
                )

    def format_prompt_header(self, max_facts: int = 6, current_frame: Any = None, current_level: Optional[int] = None) -> str:
        """Dense, token-frugal prompt block (max ~140 tokens)."""
        sections = []

        # 1. Post-Reset Lessons / Nogood Clauses
        if current_level is not None:
            lvl_ngs = self.get_nogoods_for_level(current_level)
            if lvl_ngs:
                ng_lines = ["=== POST-RESET LESSONS (DO NOT REPEAT FAILURE) ==="]
                for ng in lvl_ngs[-2:]:
                    ng_lines.append(f"- FORBIDDEN: At state '{ng.state_signature}', DO NOT execute {ng.forbidden_action}! (Reason: {ng.reason})")
                ng_lines.append("- MANDATE: At this state, explore an alternate viable action branch.")
                ng_lines.append("==================================================")
                sections.append("\n".join(ng_lines))

        # 2. Inductive Hypotheses, Local Foveated Focus & Macro-Radar from current frame
        if current_frame is not None:
            try:
                _, entities = AethelnetGameOntology.extract_entities(current_frame)
                avatar = next((e.center for e in entities if e.archetype in ("AVATAR", "ACTUATOR")), None)
                if avatar is not None:
                    patch = extract_foveated_patch(current_frame, avatar, radius=4)
                    patch_text = patch.get("ascii") or patch.get("patch_ascii") if patch else None
                    if patch_text:
                        p_lines = [f"=== LOCAL FOVEATED FOCUS (9x9 around Avatar at {avatar}) ==="]
                        p_lines.append(patch_text)
                        p_lines.append("==============================================================")
                        sections.append("\n".join(p_lines))

                radar = format_macro_radar(entities, avatar)
                if radar:
                    sections.append(radar)

                hypotheses = AethelnetGameOntology.generate_hypotheses(current_frame)
                if hypotheses:
                    h_lines = ["=== INDUCTIVE HYPOTHESES (GAME ONTOLOGY) ==="]
                    for h in hypotheses[:4]:
                        h_lines.append(f"- {h}")
                    h_lines.append("============================================")
                    sections.append("\n".join(h_lines))
            except Exception:
                pass

        # 3. Causal Facts & Scratchpad
        valid_facts = [f for f in self.facts if f.confidence >= 0.7]
        if valid_facts or self.scratchpad:
            lines = ["=== AETHELNET KNOWLEDGE VAULT ==="]
            sorted_facts = sorted(valid_facts, key=lambda x: (x.confidence, x.turn), reverse=True)[:max_facts]
            for f in sorted_facts:
                lines.append(f"- RULE: {f.subject} -> [{f.relation}] -> {f.target} (conf: {f.confidence:.2f})")

            if self.scratchpad:
                keys = list(self.scratchpad.keys())[:4]
                lines.append(f"- SCRATCHPAD CACHE: {', '.join(keys)}")

            lines.append("=================================")
            sections.append("\n".join(lines))

        return "\n\n".join(sections)

    def save(self):
        try:
            self.storage_dir.mkdir(parents=True, exist_ok=True)
            safe_scratchpad = {}
            for k, v in self.scratchpad.items():
                try:
                    json.dumps(v)
                    safe_scratchpad[str(k)] = v
                except Exception:
                    safe_scratchpad[str(k)] = str(v)[:200]

            data = {
                "game_id": self.game_id,
                "facts": [f.to_dict() for f in self.facts],
                "nogoods": [ng.to_dict() for ng in self.nogoods],
                "scratchpad": safe_scratchpad
            }
            with open(self.storage_path, "w") as f:
                json.dump(data, f, indent=2)
        except Exception:
            pass

    def load(self):
        if not self.storage_path.exists():
            return
        try:
            with open(self.storage_path, "r") as f:
                data = json.load(f)
            self.facts = [CausalFact.from_dict(d) for d in data.get("facts", [])]
            self.nogoods = [NogoodClause.from_dict(d) for d in data.get("nogoods", [])]
            self.scratchpad = data.get("scratchpad", {})
        except Exception:
            pass


def _to_lines(frame: Any) -> List[str]:
    """Converts diverse state representations into list of strings representing 2D grid."""
    if frame is None:
        return []
    if isinstance(frame, np.ndarray):
        if frame.size == 0:
            return []
        while frame.ndim > 2:
            frame = frame[0]
        if frame.ndim == 1:
            return ["".join(f"{val:X}" if isinstance(val, (int, np.integer)) else str(val) for val in frame)]
        return ["".join(f"{val:X}" if isinstance(val, (int, np.integer)) else str(val) for val in row) for row in frame]
    if hasattr(frame, 'ascii') and isinstance(frame.ascii, str):
        return [l for l in frame.ascii.splitlines() if l]
    if hasattr(frame, 'grid') and frame.grid is not None:
        return _to_lines(frame.grid)
    if isinstance(frame, list):
        if not frame:
            return []
        if isinstance(frame[0], str):
            return list(frame)
        lines = []
        for row in frame:
            if isinstance(row, (list, tuple, np.ndarray)):
                lines.append("".join(f"{val:X}" if isinstance(val, (int, np.integer)) else str(val) for val in row))
            elif isinstance(row, str):
                lines.append(row)
            else:
                lines.append(f"{row:X}" if isinstance(row, (int, np.integer)) else str(row))
        return lines
    if isinstance(frame, str):
        return [l for l in frame.splitlines() if l]
    return []



def diff_frames(f1: Any, f2: Any) -> List[Tuple[int, int, str, str]]:
    """Returns list of (row, col, old_char, new_char) that changed between f1 and f2."""
    lines1 = _to_lines(f1)
    lines2 = _to_lines(f2)
    diffs = []
    for r in range(min(len(lines1), len(lines2))):
        l1, l2 = lines1[r], lines2[r]
        for c in range(min(len(l1), len(l2))):
            if l1[c] != l2[c]:
                diffs.append((r, c, l1[c], l2[c]))
    return diffs


def read_patch(frame: Any, r1: int, r2: int, c1: int, c2: int) -> str:
    """Returns ASCII crop of region [r1..r2, c1..c2]."""
    lines = _to_lines(frame)
    if not lines:
        return ""
    rows = []
    for r in range(max(0, r1), min(len(lines), r2 + 1)):
        rows.append(lines[r][max(0, c1):min(len(lines[r]), c2 + 1)])
    return "\n".join(rows)


def find_color_centers(frame: Any, color_char: str) -> List[Tuple[int, int]]:
    """Returns (row, col) center points for all connected clusters of color_char."""
    lines = _to_lines(frame)
    if not lines:
        return []
    H = len(lines)
    W = len(lines[0]) if H > 0 else 0
    visited = set()
    centers = []
    for r in range(H):
        for c in range(W):
            if lines[r][c] == color_char and (r, c) not in visited:
                cluster = []
                queue = collections.deque([(r, c)])
                visited.add((r, c))
                while queue:
                    cr, cc = queue.popleft()
                    cluster.append((cr, cc))
                    for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                        nr, nc = cr + dr, cc + dc
                        if 0 <= nr < H and 0 <= nc < W and (nr, nc) not in visited and lines[nr][nc] == color_char:
                            visited.add((nr, nc))
                            queue.append((nr, nc))
                avg_r = int(round(sum(p[0] for p in cluster) / len(cluster)))
                avg_c = int(round(sum(p[1] for p in cluster) / len(cluster)))
                centers.append((avg_r, avg_c))
    return centers


# ---------------------------------------------------------------------------
# AETHELNET GAME ONTOLOGY & INDUCTIVE HYPOTHESIS ENGINE
# ---------------------------------------------------------------------------

@dataclass
class OntologyEntity:
    id: int
    color: str
    archetype: str  # 'AVATAR', 'GOAL', 'PUSHABLE', 'COLLECTIBLE', 'HAZARD', 'ACTUATOR', 'GATE', 'OBSTACLE', 'HUD'
    bbox: Tuple[int, int, int, int]  # (min_r, min_c, max_r, max_c)
    area: int
    is_hollow: bool = False
    inner_area: int = 0
    center: Tuple[int, int] = (0, 0)

    @property
    def dimensions(self) -> Tuple[int, int]:
        return (self.bbox[2] - self.bbox[0] + 1, self.bbox[3] - self.bbox[1] + 1)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "color": self.color,
            "archetype": self.archetype,
            "bbox": self.bbox,
            "area": self.area,
            "is_hollow": self.is_hollow,
            "inner_area": self.inner_area,
            "center": self.center,
            "dimensions": self.dimensions
        }


class AethelnetGameOntology:
    """Decomposes board into ontological archetypes and infers structural affinities."""

    @staticmethod
    def extract_entities(frame: Any) -> Tuple[str, List[OntologyEntity]]:
        lines = _to_lines(frame)
        H = len(lines)
        W = len(lines[0]) if H > 0 else 0
        if H == 0 or W == 0:
            return '.', []

        total_counts = collections.Counter("".join(lines))
        if '.' in total_counts and total_counts['.'] >= (H * W) * 0.15:
            bg_char = '.'
        elif '0' in total_counts and total_counts['0'] >= (H * W) * 0.15:
            bg_char = '0'
        else:
            border_chars = []
            for c in range(W):
                border_chars.append(lines[0][c])
                border_chars.append(lines[H - 1][c])
            for r in range(H):
                border_chars.append(lines[r][0])
                border_chars.append(lines[r][W - 1])
            counts = collections.Counter(border_chars)
            bg_char = counts.most_common(1)[0][0] if counts else (total_counts.most_common(1)[0][0] if total_counts else '.')

        visited = set()
        entities: List[OntologyEntity] = []
        ent_id = 1

        for r in range(H):
            for c in range(W):
                char = lines[r][c]
                if char != bg_char and (r, c) not in visited:
                    cluster = []
                    queue = collections.deque([(r, c)])
                    visited.add((r, c))
                    while queue:
                        cr, cc = queue.popleft()
                        cluster.append((cr, cc))
                        for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]:
                            nr, nc = cr + dr, cc + dc
                            if 0 <= nr < H and 0 <= nc < W and (nr, nc) not in visited and lines[nr][nc] == char:
                                visited.add((nr, nc))
                                queue.append((nr, nc))

                    rs = [p[0] for p in cluster]
                    cs = [p[1] for p in cluster]
                    min_r, max_r = min(rs), max(rs)
                    min_c, max_c = min(cs), max(cs)
                    area = len(cluster)
                    eh = max_r - min_r + 1
                    ew = max_c - min_c + 1
                    bbox_area = eh * ew
                    center = (int(round(sum(rs) / area)), int(round(sum(cs) / area)))

                    is_hollow = False
                    inner_area = 0
                    if eh >= 3 and ew >= 3 and area < bbox_area:
                        inner_pts = set()
                        for ir in range(min_r + 1, max_r):
                            for ic in range(min_c + 1, max_c):
                                if (ir, ic) not in cluster:
                                    inner_pts.add((ir, ic))
                        if inner_pts:
                            is_hollow = True
                            inner_area = len(inner_pts)

                    archetype = "OBSTACLE"
                    if (min_r == 0 or max_r == H - 1) and ew >= W - 4 and area >= W - 4:
                        archetype = "HUD"
                    elif is_hollow:
                        archetype = "GOAL"
                    elif (eh == 1 and ew >= 3 and 1 < min_r < H - 2) or (ew == 1 and eh >= 3 and 1 < min_c < W - 2):
                        archetype = "GATE"
                    elif area <= 9 and eh <= 3 and ew <= 3:
                        archetype = "ACTUATOR"
                    elif area <= 36 and not is_hollow:
                        archetype = "PUSHABLE"
                    elif area > 100:
                        archetype = "OBSTACLE"

                    entities.append(OntologyEntity(
                        id=ent_id,
                        color=char,
                        archetype=archetype,
                        bbox=(min_r, min_c, max_r, max_c),
                        area=area,
                        is_hollow=is_hollow,
                        inner_area=inner_area,
                        center=center
                    ))
                    ent_id += 1

        # Second pass refinement: group tiny recurring items into COLLECTIBLE
        spec_counts = collections.Counter((e.color, e.area) for e in entities)
        for e in entities:
            if e.archetype == "ACTUATOR" and spec_counts[(e.color, e.area)] >= 3:
                e.archetype = "COLLECTIBLE"

        return bg_char, entities

    @staticmethod
    def match_slot_cargo(entities: List[OntologyEntity]) -> List[Dict[str, Any]]:
        """Matches solid cargo blocks to hollow slots/receptors by dimension and shape congruence."""
        cargos = [e for e in entities if e.archetype in ("PUSHABLE", "ACTUATOR") and not e.is_hollow and e.area >= 2]
        slots = [e for e in entities if e.is_hollow or e.archetype == "GOAL"]
        matches = []

        for c in cargos:
            for s in slots:
                score = 0.0
                if s.inner_area > 0:
                    area_diff = abs(c.area - s.inner_area)
                    if area_diff == 0:
                        score += 0.5
                    elif area_diff <= 2:
                        score += 0.3
                sw, sh = s.dimensions
                cw, ch = c.dimensions
                if cw <= sw and ch <= sh:
                    score += 0.3
                if c.color == s.color:
                    score += 0.2

                if score >= 0.5:
                    matches.append({
                        "cargo_id": c.id,
                        "slot_id": s.id,
                        "cargo_color": c.color,
                        "slot_color": s.color,
                        "cargo_pos": c.center,
                        "slot_pos": s.center,
                        "score": round(score, 2)
                    })
        return sorted(matches, key=lambda x: x["score"], reverse=True)

    @staticmethod
    def detect_blueprints(frame: Any, entities: List[OntologyEntity]) -> List[Dict[str, Any]]:
        """Identifies small isolated template windows in corners that depict goal shapes."""
        lines = _to_lines(frame)
        H = len(lines)
        W = len(lines[0]) if H > 0 else 0
        if H == 0 or W == 0:
            return []
        blueprints = []

        bs = max(6, min(14, H // 3, W // 3))
        corner_boxes = [
            ("TOP_LEFT", (0, 0, bs, bs)),
            ("TOP_RIGHT", (0, max(0, W - bs), bs, W - 1)),
            ("BOTTOM_LEFT", (max(0, H - bs), 0, H - 1, min(W - 1, bs))),
            ("BOTTOM_RIGHT", (max(0, H - bs), max(0, W - bs), H - 1, W - 1)),
        ]

        for name, (r1, c1, r2, c2) in corner_boxes:
            box_ents = [e for e in entities if r1 <= e.bbox[0] and e.bbox[2] <= r2 and c1 <= e.bbox[1] and e.bbox[3] <= c2]
            colors = {e.color for e in box_ents if e.archetype != "HUD"}
            total_area = sum(e.area for e in box_ents)
            if len(colors) >= 2 and 4 <= total_area <= 60:
                blueprints.append({
                    "location": name,
                    "bbox": (r1, c1, r2, c2),
                    "colors": sorted(list(colors)),
                    "description": f"Static template in {name} with colors {sorted(list(colors))}"
                })
        return blueprints

    @staticmethod
    def detect_actuator_affordances(entities: List[OntologyEntity]) -> List[Dict[str, Any]]:
        """Maps switches/actuators to corresponding gates or goals based on color alignment."""
        actuators = [e for e in entities if e.archetype == "ACTUATOR"]
        targets = [e for e in entities if e.archetype in ("GATE", "GOAL", "OBSTACLE", "PUSHABLE")]
        affordances = []

        for act in actuators:
            for tgt in targets:
                if act.id != tgt.id and act.color == tgt.color:
                    affordances.append({
                        "actuator_id": act.id,
                        "target_id": tgt.id,
                        "color": act.color,
                        "actuator_pos": act.center,
                        "target_pos": tgt.center,
                        "target_archetype": tgt.archetype,
                        "description": f"Switch #{act.id} at {act.center} (color '{act.color}') matches {tgt.archetype} #{tgt.id} at {tgt.center}"
                    })
        return affordances

    @staticmethod
    def generate_hypotheses(frame: Any) -> List[str]:
        """Generates compact, high-confidence inductive hypotheses for LLM prompt."""
        bg_char, entities = AethelnetGameOntology.extract_entities(frame)
        if not entities:
            return []

        hypotheses = []
        matches = AethelnetGameOntology.match_slot_cargo(entities)
        for m in matches[:3]:
            hypotheses.append(
                f"[SLOT-CARGO] Entity #{m['cargo_id']} (col '{m['cargo_color']}', pos {m['cargo_pos']}) "
                f"congruent with Slot #{m['slot_id']} (col '{m['slot_color']}', pos {m['slot_pos']}) [score: {m['score']:.2f}]"
            )

        affordances = AethelnetGameOntology.detect_actuator_affordances(entities)
        for a in affordances[:2]:
            hypotheses.append(
                f"[ACTUATOR] Switch #{a['actuator_id']} at {a['actuator_pos']} (col '{a['color']}') "
                f"matches {a['target_archetype']} #{a['target_id']} at {a['target_pos']}"
            )

        blueprints = AethelnetGameOntology.detect_blueprints(frame, entities)
        for b in blueprints[:2]:
            hypotheses.append(f"[BLUEPRINT] Goal template in {b['location']} with colors {b['colors']}")

        return hypotheses


# ---------------------------------------------------------------------------
# SOKOBAN CORNER DEADLOCK & VETO ENGINE (Phase 346 / v40)
# ---------------------------------------------------------------------------

def is_corner_deadlock(
    frame_or_grid: Any,
    pos: Union[Tuple[int, int], Tuple[int, int, int, int]],
    goal_coords: Optional[Set[Tuple[int, int]]] = None,
    solid_mask: Optional[np.ndarray] = None,
    exclude_coords: Optional[Set[Tuple[int, int]]] = None
) -> bool:
    """
    Evaluates whether placing a movable solid entity at pos=(r, c) or bbox=(r1, c1, r2, c2)
    creates an irreversible 90-degree corner deadlock against non-walkable boundaries.
    """
    if len(pos) == 2:
        min_r, min_c = pos
        max_r, max_c = pos
    else:
        min_r, min_c, max_r, max_c = pos

    if goal_coords:
        for gr in range(min_r, max_r + 1):
            for gc in range(min_c, max_c + 1):
                if (gr, gc) in goal_coords:
                    return False

    mask = None
    if solid_mask is not None:
        if isinstance(solid_mask, np.ndarray) and solid_mask.ndim == 2:
            mask = solid_mask.copy()
            H, W = mask.shape
        else:
            try:
                sm = np.asarray(solid_mask, dtype=bool)
                if sm.ndim == 2:
                    mask = sm.copy()
                    H, W = mask.shape
            except Exception:
                mask = None

    if mask is None:
        lines = _to_lines(frame_or_grid)
        H = len(lines)
        W = len(lines[0]) if H > 0 else 0
        if H == 0 or W == 0:
            return False
        bg, entities = AethelnetGameOntology.extract_entities(frame_or_grid)
        mask = np.zeros((H, W), dtype=bool)

        for e in entities:
            if e.archetype in ("OBSTACLE", "HUD"):
                er1, ec1, er2, ec2 = e.bbox
                for row in range(er1, er2 + 1):
                    for col in range(ec1, ec2 + 1):
                        if lines[row][col] == e.color:
                            mask[row, col] = True

        if not np.any(mask):
            for row in range(H):
                for col in range(W):
                    if lines[row][col] != bg and lines[row][col] not in ('.', '0'):
                        mask[row, col] = True

    if exclude_coords:
        for er, ec in exclude_coords:
            if 0 <= er < H and 0 <= ec < W:
                mask[er, ec] = False

    up_blocked = (min_r <= 0) or any(mask[min_r - 1, c] for c in range(min_c, max_c + 1) if min_r - 1 < H and c < W)
    down_blocked = (max_r >= H - 1) or any(mask[max_r + 1, c] for c in range(min_c, max_c + 1) if max_r + 1 < H and c < W)
    left_blocked = (min_c <= 0) or any(mask[r, min_c - 1] for r in range(min_r, max_r + 1) if min_c - 1 < W and r < H)
    right_blocked = (max_c >= W - 1) or any(mask[r, max_c + 1] for r in range(min_r, max_r + 1) if max_c + 1 < W and r < H)

    is_corner = (up_blocked or down_blocked) and (left_blocked or right_blocked)
    return bool(is_corner)


def evaluate_push_deadlock(
    frame_or_grid: Any,
    box_pos: Union[Tuple[int, int], Tuple[int, int, int, int]],
    push_action: Union[int, str],
    goal_coords: Optional[Set[Tuple[int, int]]] = None,
    solid_mask: Optional[np.ndarray] = None
) -> Tuple[bool, Optional[str]]:
    """
    Returns (True, reason) if executing push_action on box at box_pos
    would push it into an irreversible corner deadlock.
    """
    if push_action not in ACTION_TO_DIR:
        return False, None

    if isinstance(box_pos, (list, np.ndarray)):
        box_pos = tuple(box_pos)
    dr, dc = ACTION_TO_DIR[push_action]
    if len(box_pos) == 2:
        r, c = box_pos
        target_pos = (r + dr, c + dc)
        exclude = {tuple(box_pos)}
    else:
        r1, c1, r2, c2 = box_pos
        target_pos = (r1 + dr, c1 + dc, r2 + dr, c2 + dc)
        exclude = {(r, c) for r in range(r1, r2 + 1) for c in range(c1, c2 + 1)}

    if is_corner_deadlock(frame_or_grid, target_pos, goal_coords, solid_mask=solid_mask, exclude_coords=exclude):
        return True, f"Pushing cargo from {box_pos} to {target_pos} creates permanent corner deadlock."
    return False, None


# Sandbox helper aliases
def classify_entities(frame: Any) -> List[Dict[str, Any]]:
    _, entities = AethelnetGameOntology.extract_entities(frame)
    return [e.to_dict() for e in entities]

def match_slots(entities_or_frame: Any) -> List[Dict[str, Any]]:
    if isinstance(entities_or_frame, list) and entities_or_frame and isinstance(entities_or_frame[0], OntologyEntity):
        return AethelnetGameOntology.match_slot_cargo(entities_or_frame)
    _, entities = AethelnetGameOntology.extract_entities(entities_or_frame)
    return AethelnetGameOntology.match_slot_cargo(entities)

def detect_affordances(entities_or_frame: Any) -> List[Dict[str, Any]]:
    if isinstance(entities_or_frame, list) and entities_or_frame and isinstance(entities_or_frame[0], OntologyEntity):
        return AethelnetGameOntology.detect_actuator_affordances(entities_or_frame)
    _, entities = AethelnetGameOntology.extract_entities(entities_or_frame)
    return AethelnetGameOntology.detect_actuator_affordances(entities)

def veto_deadlock_move(frame: Any, box_pos: Tuple[int, int], action: Any) -> Tuple[bool, Optional[str]]:
    _, entities = AethelnetGameOntology.extract_entities(frame)
    goals = set()
    for e in entities:
        if e.archetype == "GOAL" and e.archetype not in ("HUD", "OBSTACLE"):
            min_r, min_c, max_r, max_c = e.bbox
            for r in range(min_r, max_r + 1):
                for c in range(min_c, max_c + 1):
                    goals.add((r, c))
            goals.add(e.center)
    return evaluate_push_deadlock(frame, box_pos, action, goals)


def get_vault(game_id: str = "default", storage_dir: str = "/kaggle/working") -> AethelnetVault:
    return AethelnetVault.get_instance(game_id, storage_dir=storage_dir)


# ---------------------------------------------------------------------------
# FOVEATED SPATIAL ATTENTION & DYNAMIC MACRO-RADAR (Phase 347 / v41)
# ---------------------------------------------------------------------------

def extract_foveated_patch(
    frame_or_grid: Any,
    center: Tuple[int, int],
    radius: int = 4
) -> Dict[str, Any]:
    """
    Extracts an (2*radius + 1) x (2*radius + 1) local window centered at center=(r, c).
    Pads out-of-bounds with '#' boundary indicator.
    """
    lines = _to_lines(frame_or_grid)
    H = len(lines)
    W = len(lines[0]) if H > 0 else 0
    cr, cc = center
    r1, r2 = cr - radius, cr + radius
    c1, c2 = cc - radius, cc + radius

    patch_lines = []
    for r in range(r1, r2 + 1):
        row_chars = []
        for c in range(c1, c2 + 1):
            if 0 <= r < H and 0 <= c < W:
                row_chars.append(lines[r][c])
            else:
                row_chars.append('#')
        patch_lines.append("".join(row_chars))

    return {
        "r1": r1,
        "c1": c1,
        "r2": r2,
        "c2": c2,
        "center": (cr, cc),
        "lines": patch_lines,
        "ascii": "\n".join(patch_lines)
    }


def format_macro_radar(
    entities: List[OntologyEntity],
    avatar_pos: Optional[Tuple[int, int]] = None
) -> str:
    """
    Generates an ultra-compact semantic radar (<40 tokens) mapping
    relative offsets and Manhattan distances from the avatar to key landmarks.
    """
    if not entities:
        return ""
    lines = ["=== AETHELNET MACRO-RADAR ==="]
    if avatar_pos is not None:
        lines.append(f"- AVATAR: at {avatar_pos}")

    targets = [e for e in entities if e.archetype in ("GOAL", "PUSHABLE", "ACTUATOR", "GATE", "HAZARD")]
    if avatar_pos is not None:
        targets.sort(key=lambda e: abs(e.center[0] - avatar_pos[0]) + abs(e.center[1] - avatar_pos[1]))

    for e in targets[:5]:
        if avatar_pos is not None:
            dr = e.center[0] - avatar_pos[0]
            dc = e.center[1] - avatar_pos[1]
            dist = abs(dr) + abs(dc)
            lines.append(f"- {e.archetype} #{e.id} (col '{e.color}'): at {e.center} [Offset: ({dr:+d}, {dc:+d}), Dist: {dist}]")
        else:
            lines.append(f"- {e.archetype} #{e.id} (col '{e.color}'): at {e.center}")

    lines.append("=============================")
    return "\n".join(lines)


def track_entity_velocities(
    prev_entities: List[OntologyEntity],
    curr_entities: List[OntologyEntity]
) -> List[Dict[str, Any]]:
    """
    Computes velocity vectors v = (dr, dc) across consecutive frames
    for matching non-HUD entities.
    """
    velocities = []
    for ce in curr_entities:
        if ce.archetype in ("HUD", "OBSTACLE"):
            continue
        best_match = None
        min_dist = 999
        for pe in prev_entities:
            if pe.color == ce.color and pe.archetype == ce.archetype:
                d = abs(ce.center[0] - pe.center[0]) + abs(ce.center[1] - pe.center[1])
                if d < min_dist and d <= 6:
                    min_dist = d
                    best_match = pe
        if best_match is not None and min_dist > 0:
            dr = ce.center[0] - best_match.center[0]
            dc = ce.center[1] - best_match.center[1]
            dir_name = "STATIONARY"
            if dr < 0 and dc == 0: dir_name = "UP"
            elif dr > 0 and dc == 0: dir_name = "DOWN"
            elif dr == 0 and dc < 0: dir_name = "LEFT"
            elif dr == 0 and dc > 0: dir_name = "RIGHT"
            elif dr < 0 and dc > 0: dir_name = "UP_RIGHT"
            elif dr < 0 and dc < 0: dir_name = "UP_LEFT"
            elif dr > 0 and dc > 0: dir_name = "DOWN_RIGHT"
            elif dr > 0 and dc < 0: dir_name = "DOWN_LEFT"

            velocities.append({
                "entity_id": ce.id,
                "color": ce.color,
                "archetype": ce.archetype,
                "pos": ce.center,
                "velocity": (dr, dc),
                "direction": dir_name
            })
    return velocities


def simulate_step(
    frame_or_grid: Any,
    action: Union[int, str],
    avatar_pos: Optional[Tuple[int, int]] = None
) -> Tuple[List[str], bool, List[str]]:
    """
    Performs a deterministic 1-step virtual simulation of action from avatar_pos.
    Returns (predicted_lines, is_deadlock, event_log).
    """
    lines = [list(row) for row in _to_lines(frame_or_grid)]
    H = len(lines)
    W = len(lines[0]) if H > 0 else 0
    if H == 0 or W == 0 or action not in ACTION_TO_DIR:
        return ["".join(r) for r in lines], False, ["Invalid action or empty frame"]

    dr, dc = ACTION_TO_DIR[action]
    events = []

    bg, entities = AethelnetGameOntology.extract_entities(frame_or_grid)
    ar, ac = avatar_pos if avatar_pos is not None else (0, 0)
    if avatar_pos is None:
        for e in entities:
            if e.archetype == "ACTUATOR":
                ar, ac = e.center
                break

    nr, nc = ar + dr, ac + dc
    if not (0 <= nr < H and 0 <= nc < W):
        events.append("Hit board boundary")
        return ["".join(r) for r in lines], False, events

    target_char = lines[nr][nc]
    is_deadlock = False

    cargos = [e for e in entities if e.archetype in ("PUSHABLE", "ACTUATOR") and not e.is_hollow and e.center != (ar, ac)]
    matching_cargo = None
    for c in cargos:
        r1, c1, r2, c2 = c.bbox
        if r1 <= nr <= r2 and c1 <= nc <= c2:
            matching_cargo = c
            break

    if matching_cargo is not None:
        deadlock, reason = evaluate_push_deadlock(frame_or_grid, matching_cargo.bbox, action)
        if deadlock:
            is_deadlock = True
            events.append(f"Push causes deadlock: {reason}")
        else:
            events.append(f"Pushed cargo #{matching_cargo.id} in direction {action}")
            lines[nr][nc] = bg
            target_br, target_bc = matching_cargo.center[0] + dr, matching_cargo.center[1] + dc
            if 0 <= target_br < H and 0 <= target_bc < W:
                lines[target_br][target_bc] = matching_cargo.color
    elif target_char != bg and target_char not in ('.', '0'):
        events.append(f"Collided with obstacle '{target_char}'")
    else:
        events.append(f"Avatar moved to ({nr}, {nc})")

    return ["".join(r) for r in lines], is_deadlock, events


# ---------------------------------------------------------------------------
# MACRO-ACTION INTENT COMPILER & OPTIONS FRAMEWORK (Phase 348 / v42)
# ---------------------------------------------------------------------------

@dataclass
class MacroIntent:
    name: str  # 'NAVIGATE_TO', 'PUSH_BOX', 'ACTUATE_SWITCH', 'INTERACT'
    target: Optional[Tuple[int, int]] = None
    box_pos: Optional[Tuple[int, int]] = None
    direction: Optional[str] = None  # 'UP', 'DOWN', 'LEFT', 'RIGHT'
    entity_id: Optional[int] = None
    params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MacroChainResult:
    success: bool
    actions: List[Dict[str, Any]]
    action_names: List[str]
    reason: str
    step_count: int


class AethelnetMacroCompiler:
    """Compiles high-level macro intents into verified atomic action sequences."""

    @classmethod
    def compile_intent(
        cls,
        intent: Union[MacroIntent, Dict[str, Any]],
        frame_or_grid: Any,
        solid_mask: Optional[np.ndarray] = None,
        avatar_pos: Optional[Tuple[int, int]] = None,
        stride: int = 1,
        available_actions: Optional[List[Any]] = None
    ) -> MacroChainResult:
        if isinstance(intent, dict):
            intent = MacroIntent(
                name=intent.get("name", intent.get("intent", "")),
                target=intent.get("target"),
                box_pos=intent.get("box_pos"),
                direction=intent.get("direction"),
                entity_id=intent.get("entity_id"),
                params=intent.get("params", {})
            )

        lines = _to_lines(frame_or_grid)
        H = len(lines)
        W = len(lines[0]) if H > 0 else 0
        if H == 0 or W == 0:
            return MacroChainResult(False, [], [], "EmptyGrid", 0)

        # 0. Defensive parameter resolution for solid_mask / available_actions
        if isinstance(solid_mask, (list, tuple)) and solid_mask and not isinstance(solid_mask[0], (list, tuple, np.ndarray)):
            if available_actions is None:
                available_actions = list(solid_mask)
            solid_mask = None

        if solid_mask is not None:
            if isinstance(solid_mask, np.ndarray) and solid_mask.ndim == 2 and solid_mask.shape == (H, W):
                solid_mask = solid_mask.copy()
            else:
                try:
                    sm = np.asarray(solid_mask, dtype=bool)
                    if sm.ndim == 2 and sm.shape == (H, W):
                        solid_mask = sm.copy()
                    else:
                        solid_mask = None
                except Exception:
                    solid_mask = None

        # 1. Resolve Avatar Position if not explicitly given
        if avatar_pos is None:
            _, entities = AethelnetGameOntology.extract_entities(frame_or_grid)
            av_entity = next((e for e in entities if e.archetype in ("AVATAR", "ACTUATOR")), None)
            if av_entity:
                avatar_pos = av_entity.center
            else:
                avatar_pos = (H // 2, W // 2)

        # 2. Build or resolve solid_mask
        if solid_mask is None:
            solid_mask = np.zeros((H, W), dtype=bool)
            bg, entities = AethelnetGameOntology.extract_entities(frame_or_grid)
            for r in range(H):
                for c in range(W):
                    if lines[r][c] != bg and lines[r][c] not in ('.', '0'):
                        solid_mask[r, c] = True
            # Avatar tile itself is walkable
            if 0 <= avatar_pos[0] < H and 0 <= avatar_pos[1] < W:
                solid_mask[avatar_pos[0], avatar_pos[1]] = False

        intent_name = (intent.name or "").upper()

        # CASE 1: NAVIGATE_TO
        if intent_name in ("NAVIGATE_TO", "NAVIGATE", "MOVE_TO"):
            target = intent.target
            if target is None:
                return MacroChainResult(False, [], [], "MissingTarget", 0)
            tr, tc = target
            if not (0 <= tr < H and 0 <= tc < W):
                return MacroChainResult(False, [], [], "TargetOutOfBounds", 0)

            # Ensure target tile is temporarily marked walkable for path search
            orig_solid = solid_mask[tr, tc]
            solid_mask[tr, tc] = False
            raw_path = plan_bfs_path(avatar_pos, (tr, tc), solid_mask, stride=stride, as_strings=False)
            solid_mask[tr, tc] = orig_solid

            if not raw_path:
                if abs(avatar_pos[0] - tr) < stride and abs(avatar_pos[1] - tc) < stride:
                    return MacroChainResult(True, [], [], "AlreadyAtTarget", 0)
                return MacroChainResult(False, [], [], "PathNotFound", 0)

            action_names = [ACTION_TO_NAME.get(m, DIR_TO_ACTION_NAME.get(ACTION_TO_DIR.get(m, (0, 0)), 'UP')) for m in raw_path]
            actions = [{"action": DIR_TO_ACTION_NAME.get(ACTION_TO_DIR.get(m, (0, 0)), 'ACTION1')} for m in raw_path]
            return MacroChainResult(True, actions, action_names, "NavigationSuccess", len(actions))

        # CASE 2: PUSH_BOX
        elif intent_name in ("PUSH_BOX", "PUSH"):
            box_pos = intent.box_pos or intent.target
            if isinstance(box_pos, (list, np.ndarray)):
                box_pos = tuple(box_pos)
            direction = (intent.direction or "UP").upper()
            if box_pos is None:
                return MacroChainResult(False, [], [], "MissingBoxPos", 0)

            dir_map = {"UP": (-1, 0), "DOWN": (1, 0), "LEFT": (0, -1), "RIGHT": (0, 1)}
            if direction not in dir_map:
                return MacroChainResult(False, [], [], f"InvalidDirection_{direction}", 0)
            dr, dc = dir_map[direction]

            # Deadlock check: does pushing box in this direction cause corner deadlock?
            deadlock, reason = evaluate_push_deadlock(frame_or_grid, box_pos, direction, solid_mask=solid_mask)
            if deadlock:
                return MacroChainResult(False, [], [], f"DeadlockVeto_{reason}", 0)

            # Push pose: tile directly opposite to push direction
            push_pose = (box_pos[0] - dr * stride, box_pos[1] - dc * stride)
            if not (0 <= push_pose[0] < H and 0 <= push_pose[1] < W):
                return MacroChainResult(False, [], [], "PushPoseOutOfBounds", 0)

            # Route avatar to push_pose avoiding box
            box_barrier = solid_mask.copy()
            box_barrier[box_pos[0], box_pos[1]] = True
            box_barrier[push_pose[0], push_pose[1]] = False

            nav_moves = plan_bfs_path(avatar_pos, push_pose, box_barrier, stride=stride, as_strings=False)
            if avatar_pos != push_pose and not nav_moves:
                return MacroChainResult(False, [], [], "CannotReachPushPose", 0)

            push_act_int = DIR_TO_ACTION_INT.get((dr, dc), 1)
            total_moves = nav_moves + [push_act_int]
            action_names = [ACTION_TO_NAME.get(m, 'UP') for m in total_moves]
            actions = [{"action": DIR_TO_ACTION_NAME.get(ACTION_TO_DIR.get(m, (0, 0)), 'ACTION1')} for m in total_moves]
            return MacroChainResult(True, actions, action_names, "PushPlanSuccess", len(actions))

        # CASE 3: ACTUATE_SWITCH / CLICK / INTERACT
        elif intent_name in ("ACTUATE_SWITCH", "ACTUATE", "INTERACT", "MOUSE"):
            target = intent.target
            if target is None:
                return MacroChainResult(False, [], [], "MissingTarget", 0)

            # If parameter specifies MOUSE click:
            if intent_name in ("INTERACT", "MOUSE") or intent.params.get("use_mouse"):
                act = {"action": "MOUSE", "row": target[0], "col": target[1]}
                return MacroChainResult(True, [act], ["MOUSE"], "MouseAction", 1)

            # Check if game supports ACTION5 (Interact/Use)
            has_action5 = False
            if available_actions:
                act_vals = [getattr(a, 'value', a) for a in available_actions]
                has_action5 = (5 in act_vals or "ACTION5" in act_vals)

            # Otherwise, route to adjacent cell and interact
            adj_cells = [
                (target[0] - dr * stride, target[1] - dc * stride)
                for dr, dc in [(-1, 0), (1, 0), (0, -1), (0, 1)]
            ]
            valid_adj = [p for p in adj_cells if 0 <= p[0] < H and 0 <= p[1] < W and not solid_mask[p[0], p[1]]]
            if not valid_adj:
                return MacroChainResult(False, [], [], "SwitchUnreachable", 0)

            # Pick nearest adjacent tile to avatar
            valid_adj.sort(key=lambda p: abs(p[0] - avatar_pos[0]) + abs(p[1] - avatar_pos[1]))
            best_adj = valid_adj[0]

            nav_moves = plan_bfs_path(avatar_pos, best_adj, solid_mask, stride=stride, as_strings=False)

            if has_action5:
                # Face target or trigger ACTION5 interact
                action_names = [ACTION_TO_NAME.get(m, 'UP') for m in nav_moves] + ["ACTION5"]
                actions = [{"action": DIR_TO_ACTION_NAME.get(ACTION_TO_DIR.get(m, (0, 0)), 'ACTION1')} for m in nav_moves] + [{"action": "ACTION5"}]
            else:
                step_to_switch_dr, step_to_switch_dc = target[0] - best_adj[0], target[1] - best_adj[1]
                # Normalize step to unit direction
                norm_dr = 1 if step_to_switch_dr > 0 else (-1 if step_to_switch_dr < 0 else 0)
                norm_dc = 1 if step_to_switch_dc > 0 else (-1 if step_to_switch_dc < 0 else 0)
                act_step = DIR_TO_ACTION_INT.get((norm_dr, norm_dc), 1)
                total_moves = nav_moves + [act_step]
                action_names = [ACTION_TO_NAME.get(m, 'UP') for m in total_moves]
                actions = [{"action": DIR_TO_ACTION_NAME.get(ACTION_TO_DIR.get(m, (0, 0)), 'ACTION1')} for m in total_moves]

            return MacroChainResult(True, actions, action_names, "ActuateSuccess", len(actions))

        return MacroChainResult(False, [], [], f"UnknownIntent_{intent.name}", 0)




